const Sequelize = require("sequelize");
const sequelize = require('../db_management/sequelize');

const Comm = sequelize.define("Comm", {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
    },
    datetime: {
        type: Sequelize.DATE,       // DATE = DATETIME for mysql
        allowNull: false,
    },
    author: {                       // used to quicker the frontend jobs
        type: Sequelize.STRING,     // STRING = VARCHAR(255)
        allowNull: false,
    },
    text: {
        type: Sequelize.TEXT,
        allowNull: false,
    }
    // OTHER COLUMNS ARE FOREIGN KEYS GENERATED BY SEQUELIZE : userId and postId
});

 module.exports = Comm;