const Sequelize = require("sequelize");
const sequelize = require('../db_management/sequelize');

const Like = sequelize.define("Like", {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
    },
    pseudo: {
        type: Sequelize.STRING,     // STRING = VARCHAR(255)
        allowNull: false,
    },
    userId: {
        type: Sequelize.INTEGER,
        allowNull: false,
    }
    // OTHER COLUMNS ARE FOREIGN KEYS GENERATED BY SEQUELIZE : PostId
});

module.exports = Like;