const Sequelize = require("sequelize");
const sequelize = require('../db_management/sequelize');

const Like = sequelize.define("Like", {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
    }
    // OTHER COLUMNS ARE FOREIGN KEYS GENERATED BY SEQUELIZE : userId and postId
});

module.exports = Like;